### ISSUE TITLE
Release v0.0.1

### ISSUE THREAD

**Issue by jnnr** [rl-institut/oemof-B3#104]
A first release is possible as soon as the first scenarios run. Use this issue to collect the todos for the actual release process. We use oemof's how to release as an orientation (See a boiled-down version of the release todos below): https://github.com/oemof/oemof/wiki/How-to-release

### Preparation
* Finish issues and PRs related to the release https://github.com/rl-institut/oemof-B3/milestones/v0.0.1
* Test the examples
* Keep an eye on open issues that are set to your release but seem to be forgotten.
* Setup zenodo hook
* [x] Check that the docs look good. #139 
* [x] check that oemoflex contains all necessary features/fixes
* [x] keep toy-scenarios? No, deleted
* [x] check headers of python scripts #158
 
### Day of release
* Optional: Open a release branch to avoid conflicts with other uses while the release progress.
* [x] Close "forgotten" issues with a recapitulatory comment or set them to a later release if they are still important.
* Test if it works
  * [x] Install in a fresh environment
  * [x] Examples
  * [x] Scenarios
  * [x] Plots
  * [x] Tables
  * [x] Reports
  * [x] Check for obsolete snakemake rules/options (fix them in #155) 
* If you have failing test fix them or postpone the release.
* Check the whatsnew-file 
* Check if the *latest* documentation looks right at readthedocs.
* Change the version number everywhere!!! [TODO] (e.g. from 0.2.1dev to 0.2.1) -> `pyproject.yaml` and `docs/conf.py`
* If everything seems to work, merge the release branch into the main branch. (--no-ff)
* Push your local main branch to the remote.
* Set a [release on github](../releases). Select the **main** branch (default: dev)! A label is set automatically.
* Use `git fetch` to see the label in your local main branch.
* Merge the release branch into the dev branch. (--no-ff)
* Remove the obsolete release branch.
* Prepare the dev branch for further development: Adapt the version number at (e.g. from 0.2.1 to 0.2.2dev). Also add a new whatsnew file and a link in the [whatsnew.rst file](../tree/dev/doc/whats_new.rst). Open the file locally or use the *RAW* button to see the links.
* Edit-Zenodo-entry
* Close the release issue with informations for the community and relax
