### ISSUE TITLE
Revise docs

### ISSUE THREAD

**Issue by MaGering** [rl-institut/oemof-B3#119]
The docs are partly outdated and need to be revised.

1. Parts that need revisions must be identified
2. Missing info must be added

Open docs issues:
- https://github.com/rl-institut/oemof-B3/issues/3 (Milestone v0.01)
- https://github.com/rl-institut/oemof-B3/issues/81 (No milestone set yet)

**Comment by MaGering** [comment]
**Tasks can be collected here**

1. Parts that need revision:
   - [ ] Update description in [Examples](https://github.com/rl-institut/oemof-B3/blob/dev/docs/examples.rst)
   - [ ] Adapt variables under [Elements](https://github.com/rl-institut/oemof-B3/blob/dev/docs/model_structure.rst) to the ones appearing in [schema](https://github.com/rl-institut/oemof-B3/tree/dev/oemof_b3/schema)
   - [ ] Revise [Model pipeline](https://oemof-b3.readthedocs.io/en/latest/model_pipeline.html)
       - [ ] ...
       - [ ] ...
   - [ ] ... 

2. Info to be added:
   - [ ] ... 
       - [ ] ...
       - [ ] ...

**Comment by monika-o** [comment]
The above list has got quite extensive. In my opinion, the most important tasks are the revision of the model pipeline, simply because it looks very incomplete, and a documentation of what @SabineHaas wrote in https://github.com/rl-institut/oemof-B3/issues/81.

**Comment by MaGering** [comment]
Some docstrings are not rendered with `automodule` in [Model pipeline](https://oemof-b3.readthedocs.io/en/latest/model_pipeline.html). @jnnr can you help with this?

**Comment by jnnr** [comment]
To give a better intro into the model pipeline, we can add a graphic of the DAG, like this
![dag](https://user-images.githubusercontent.com/32454596/156008161-ab7b70dc-dee0-448c-be02-a15fc73415d3.jpg)

**Comment by MaGering** [comment]
> * (v0.0.2) Links in "getting started" are not rendered - no correct rtf syntax.

@monika-o , @jnnr: Do any of you know what is meant by this? I don't see any links that are not rendered. I would otherwise remove this item from the ckeckbox list.

**Comment by MaGering** [comment]
> There are two links in the installation section where the text that should clickable as link is displayed in square brackets and the actual link (which should be hidden) follows in normal brackets. This concerns pandoc installation and oemof.solph.

Thanks for specifying @monika-o. Looks like this was supposed to be a feature and not a bug ;-) However, I fixed this with commit https://github.com/rl-institut/oemof-B3/pull/263/commits/506d18075dcab6535a3ee1339511745bbea4770b in PR https://github.com/rl-institut/oemof-B3/pull/263.

**Comment by monika-o** [comment]
Time has passed and I have a few new comments:
[ ] The windows issue with snakemake is closed now, but in the docs it says that it's open. I don't know whether the problem itself has been solved.
[ ] Are the first full scenario now available? (In overview we say that they will be made available in the coming months)
[ ] [upload_b3_data_to_oep](file:///home/monika/Documents/RLI/oemof-B3/docs/_build/html/oep_upload_download/upload_b3_data_to_oep.html) is empty.

**Comment by MaGering** [comment]
Thanks for looking into it @monika-o 

> [ ] The windows issue with snakemake is closed now, but in the docs it says that it's open. I don't know whether the problem itself has been solved.

Could you write an issue for this? It has to be checked if the snakemake execution works with windows by now.

> [ ] Are the first full scenario now available? (In overview we say that they will be made available in the coming months)

Thanks I took it out.

> [ ] upload_b3_data_to_oep is empty.

I fixed this with commit https://github.com/rl-institut/oemof-B3/pull/313/commits/13ea89fbab5dc636984b91b4336f31364a19735c. However download_resources.py needs a docstring, that can be displayed in the model pipeline (I just added download_resources there because it was missing). Could you write an issue for this too?

**Comment by MaGering** [comment]
> [ ] (v0.0.3) Provide more information about the input data
> 
>     * [ ]  How can a maximum capacity be implemented? If there is only a single capacity value, what does it mean?

@Stefanie08 I think we've already looked at this but could you check if we have this covered? Basic message should be:

- Already installed capacity is provided with the attribute `capacity` (e.g. 0 if Greenfield and other positive numeric value if Brownfield)
- A maximum capacity is set with a positive numeric value for the attribute `capacity_potential`. An empty `capacity_potential` corresponds to an infinite capacity potential.

Actually, this should be documented in `oemof.facades`. But maybe you can find it in `oemoflex` or [here](https://oemof-b3.readthedocs.io/en/latest/model_pipeline.html#conventions) in this repo. I would plead for it to be added here in the repo if it is not documented in the other two, to at least have it somewhere.

**Comment by MaGering** [comment]
> * I would remove the _contents_ section in the beginning of each page because it is redundant with the side panel.

Could you do this in PR https://github.com/rl-institut/oemof-B3/pull/327 as well @Stefanie08? I think it should not take too much time. Thank you!

**Comment by Stefanie08** [comment]
The contents section is removed with commit 88548e1ccd7866ca46acfd407d92d49458d5eb3b.
The description for the maximum capacity and the already installed capacity is done with commit  e1a67d1e441f19d6dcb40370d44a4438b0207b37.
